version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      - INFLUXDB_DB=mydb
  ntpinflux:
    container_name: ntpinfluxdb
    build: ntp-influxdb
    volumes:
      - ./hostlist.txt:/usr/src/app/hostlist.txt
